### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by NazmiAltun** [notatestuser/mockizen#1]
Cool stuff. It would be more convenient if you publish this  as a docker image. 
Currently , I am using it  as below. However, I am not sure if  this is optimal way to do it.

**Dockerfile**
```
FROM node:current-alpine
WORKDIR /opt/app
RUN npm i mockizen
WORKDIR /opt/app/node_modules/mockizen
CMD ["node","--harmony","./bin/mockizen","../../mocks/scenarios.json"]

```

**docker-compose.yml**

```
mockserver:
    image: mock:latest
    build:
      context: .
    volumes:
      - ./mockserver/mocks:/opt/app/mocks
    expose:
      - "8080"
    ports:
      - "8095:8080"
```

It is working for me, but it would be easier   to pull the image  and run it.
